### ISSUE TITLE
Code formatting update

### ISSUE THREAD

**Issue by carlashworth** [big-band-roulette/musicians-portal#43]
When developing in jinja, I use a syntax highligher that provides best practice, and automatically lints, for that file type. Since we have been concurrently developing, this has picked up a lot of minor things, and I would like to sort these so that the code is cohesive.

Here are a few screenshots of the linter issues:

![image](https://github.com/big-band-roulette/musicians-portal/assets/62384616/fbc9b66a-afa1-4b3c-8d9b-951ae136a068)

![image](https://github.com/big-band-roulette/musicians-portal/assets/62384616/c4c74f79-1f01-405d-a9c7-8509225188ae)

These should be easily fixable, but make developing bug free jinja a tad more difficult. If you don't mind me fixing them, I can make one pr sorting all files immediately?

**Comment by THargreaves** [comment]
Happy to fix these and use the longer going forwards. What is the VSC extension called?

Related, the reason why you don’t have new lines at the end of files is that VSC defaults (against common practice) to removing trailing white space.

See https://m.youtube.com/watch?v=PnAhwKYhIjs to enable it.

**Comment by carlashworth** [comment]
The extensions are djLint, and Better Jinja - it's an auto linter so I think you have to install something, I can't remember, but the names are in the readme.

![image](https://github.com/big-band-roulette/musicians-portal/assets/62384616/78e63aff-53ce-4dad-8d77-6cb85a6bac6e)

**Comment by carlashworth** [comment]
#48ae623 solves this. Apologies for the bad naming...
