### ISSUE TITLE
Users need to be able to choose performer/arranger/singer  on account creation.

### ISSUE THREAD

**Issue by carlashworth** [big-band-roulette/musicians-portal#5]
- This should be a functionality that they can then update afterwards if needed?

**Comment by THargreaves** [comment]
Likewise, I'm adding fields and UI for updating your student status (e.g. are you a student, what uni, what college?).

It might be best to have this as a post-registration page to avoid us messing with the flask-security defaults.

**Comment by THargreaves** [comment]
See #37 #38 too.

**Comment by carlashworth** [comment]
Closing this to keep account creation updates in one up-to-date issue.
