### ISSUE TITLE
Update Profiles Page

### ISSUE THREAD

**Issue by carlashworth** [big-band-roulette/musicians-portal#8]
- “Instruments” section
- “You are not in the pool for any instruments…go to auditions”
- You have these… (you can go to auditions to get more”
- For each instrument: (tuned percussion is an instrument)
- Extra details: range (hard-coding), seat preferences
- Sax is its own instrument with alto 1/2, tenor 1/2 , bari seats
- Doubling:
- Add a note saying these are doublings we expect and if you double an instrument not listed we will do a call out when needed
- Bass: double
- Drums: bongos
- Tuned percussion: bongos
- Sax: flute, clarinet, sop sax
- Trumpet: flugal horn
- Trombone: tuba, sousaphone
- Notifications:
- Notify about new gigs
- Notify me about drop-outs
- Theme suggestions and preferences

**Comment by THargreaves** [comment]
All major parts of this issue are now sorted. Just need to add some explanatory text
